fix(ci): same commit error

diff --git a/.github/workflows/tourney.yml b/.github/workflows/tourney.yml
--- a/.github/workflows/tourney.yml
+++ b/.github/workflows/tourney.yml
@@ -62,6 +62,11 @@ jobs:
             *) new="${{ inputs.new_version }}" ;;
           esac
 
+          if "$(git rev-parse "$old")" = "$(git rev-parse "$new")"; then
+            echo "::error title=Identical Versions::The old ({{ inputs.old_version }}) and new ({{ inputs.new_version }}) points to the same commit."
+            exit 1
+          fi
+
           mkdir exe
 
           cargo build --release --bin=game-info
